### ISSUE TITLE
Readouts and calo cell position

### ISSUE THREAD

**Issue by BrieucF** [HEP-FCC/k4RecCalorimeter#7]
LAr calo cell positions used to be derived in several step, relying on [CreateVolumePositions](https://github.com/BrieucF/FCCSW/blob/geometry_change_rebased/Detector/DetComponents/src/CreateVolumePositions.cpp) and two different readouts (see e.g. [runCaloSim.py](https://github.com/HEP-FCC/k4RecCalorimeter/blob/main/RecFCCeeCalorimeter/tests/options/runCaloSim.py)). This feature should be recovered and/or refactored.

**Comment by vvolkl** [comment]
Since edm4hep does not have two different types for Calo hits with  / without position I don't think a separate algorithm like this makes sense. Looking at the workflow you linked, I think the positon should be set directly in `CreateCaloCells`. I'll try to refactor the code into a tool and add it there

**Comment by giovannimarchiori** [comment]
the segmentation classes could be modified and calculate the good position, without relying on the G4 volume position (which is what causes the position stored with saveCells to be crappy), but anyway now we have the CreatePositionedCaloCells alg that is like CreateCaloCells but uses a handle to a positioning tool to position the cells so maybe we can close this issue @BrieucF ?

**Comment by BrieucF** [comment]
Agreed
